project_name: hios

env:
  - GO111MODULE=on

build:
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w -X github.com/innet8/hios/version.Version={{ .Version }} -X github.com/innet8/hios/version.CommitSHA={{ .ShortCommit }}
  main: main.go
  binary: hios
  goos:
    - darwin
    - linux
  goarch:
    - amd64
    - arm64
